version: "3.9"
services:
  mysql:
    image: mysql:5.7.38
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 882434
      MYSQL_DATABASE: eop
    ports:
      - "3306:3306"
    volumes:
      - './mysql5738:/var/lib/mysql'
      - './5738conf:/etc/mysql/mysql.conf.d'
    container_name: mysql5738
    hostname: mysql5738
    networks:
      - eop
  tomcat:
    depends_on:
      - mysql
    image: tomcat:9.0.63-jdk11-temurin
    ports:
      - "8080:8080"
    volumes:
      - './webapps:/usr/local/tomcat/webapps'
    hostname: tomcat
    container_name: tomcat
    networks:
      - eop
  nginx:
    depends_on:
      - tomcat
    image: nginx:1.21.6
    ports:
      - "80:80"
    hostname: nginx
    container_name: nginx
    networks:
      - eop
networks:
  eop:
    name: eopnetwork

